### ISSUE TITLE
outage in europe-west3 (Frankfurt)

### ISSUE THREAD

**Issue by xeruf** [kubernetes/registry.k8s.io#115]
My cluster is failing, unable to pull an image, and http://registry.k8s.io also spills out errors.
Is something going on here?

**Comment by BenTheElder** [comment]
Can you please share more details?
We're not aware of an outage.

**Comment by BenTheElder** [comment]
@ameukam may have found something affecting europe-west3 (GCP) that should resolved now xref: https://github.com/kubernetes/k8s.io/pull/4337

**Comment by xeruf** [comment]
thanks, I am in Germany and our whole company was grinding to a halt as our tooling was awaiting the image :/ was able to switch to k8s.gcr.io in the meantime

**Comment by BenTheElder** [comment]
k8s.gcr.io will be redirected to registry.k8s.io in the near future, so we should make sure the issue is resolved 😅 

a small rollout will be coming next week.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#urgent-upgrade-notes-3

**Comment by winggundamth** [comment]
I'm from Thailand and having a problem with registry.k8s.io too.

```
$ docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343@sha256:39c5b2e3310dc4264d638ad28d9d1d96c4cbb2b2dcfb52368fe4e3c63f61e10f
Error response from daemon: unauthorized: not authenticated: No valid credential was supplied.
```

My GKE in SG region

```
Failed to pull image "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.3.0@sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/ingress-nginx/kube-webhook-certgen@sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47": failed to resolve reference "registry.k8s.io/ingress-nginx/kube-webhook-certgen@sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47": failed to do request: Head "https://asia-southeast1-docker.pkg.dev/v2/k8s-artifacts-prod/images/ingress-nginx/kube-webhook-certgen/manifests/sha256:549e71a6ca248c5abd51cdb73dbc3083df62cf92ed5e6147c780e30f7e007a47": failed to authorize redirect: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

**Comment by BenTheElder** [comment]
@winggundamth thats not clearly related to the root cause of the original post here. Can you please file another issue with more details about your environment

**Comment by ameukam** [comment]
@xeruf Any issue again ? Can we call this done ?

**Comment by winggundamth** [comment]
For me I can confirm everything is working as expect now.

**Comment by BenTheElder** [comment]
Will reopen if we see anything further, or you can comment `/reopen` and the bot will reopen.
This should be resolved, with no further reports.
