### ISSUE TITLE
Firewall filtering by FQDN

### ISSUE THREAD

**Issue by mozts2005** [kubernetes/registry.k8s.io#127]
Is there a list of FQDNS used in the hosting of registry.k8s.io that should be allowed by enterprise security teams to ensure access?

**Comment by BenTheElder** [comment]
No, currently we recommend mirroring instead if you need to allowlist domains.

https://github.com/kubernetes/registry.k8s.io#stability

**Comment by ameukam** [comment]
As mentioned before, mirroring the container images is the safe option in case an allowlist need to be change to allow image pulling. 

Please, reopen this issue if there is a problem during image pulling.

/close

**Comment by therevoman** [comment]
Reviving.  
Mirroring is great, but how is mirroring going to help when I can't get to the artifacts to mirror them.?

**Comment by BenTheElder** [comment]
You'll have to import them from an unrestricted host, or the the risk of depending on observed but undocumented backends.

See https://registry.k8s.io#stability

our hosts are subject to change at any tkme
