### ISSUE TITLE
get image tag from registry.k8s.io

### ISSUE THREAD

**Issue by willzhang** [kubernetes/registry.k8s.io#128]
i want search `registry.k8s.io/dns/k8s-dns-node-cache` image's tag ,how can i do that?

**Comment by BenTheElder** [comment]
It supports the OCI APIs so you can use something like `crane ls registry.k8s.io/dns/k8s-dns-node-cache` however I highly recommend looking at that project's releases instead of picking tags directly.

There is also https://explore.ggcr.dev/?repo=registry.k8s.io/dns/k8s-dns-node-cache

**Comment by ameukam** [comment]
There are several open-source to get tags from a container image.
- crane: https://github.com/google/go-containerregistry/tree/main/cmd/crane
- imgpkg: https://carvel.dev/imgpkg/docs/v0.34.0/commands/#tag

Considering this as addressed
/close
