### ISSUE TITLE
Unable to pull coredns:v1.9.3 at Uganda.

### ISSUE THREAD

**Issue by chhsiao1981** [kubernetes/registry.k8s.io#134]
Not exactly sure what happened,

but we are unable to pull coredns:v1.9.3 from registry.k8s.io,
while we can pull coredns:v1.9.3 from k8s.gcr.io.

We can successfully pull coredns:v1.9.3 from registry.k8s.io at Boston, MA though.

The dns lookup from Uganda shows that the IP of registry.k8s.io is 34.107.244.51.

**Comment by ameukam** [comment]
@chhsiao1981 what command did you use to ? And what's the error you got ?

**Comment by chhsiao1981** [comment]
hi @ameukam 

Thank you so much for the immediate reply.

The following is what I did:

<img width="2337" alt="image" src="https://user-images.githubusercontent.com/2970164/205396959-dd5cc6f4-f049-45a6-9c4c-7539f807cdd2.png">

**Comment by ameukam** [comment]
Looks like a network issue. Could be DNS. 

There are currently no specific policies for a GCP region or a specific country defined on the infrastructure.

what are the results of:
`curl -I https://registry.k8s.io/v2/manifests/pause/tags/list`
`curl https://gcping.com/api/ping` ?

**Comment by chhsiao1981** [comment]
hi @ameukam ～

Thank you so much for the quick reply.

My public IP: 137.63.178.120

<img width="705" alt="image" src="https://user-images.githubusercontent.com/2970164/205399468-029dccd0-d94e-4259-92f3-2a9901c77479.png">


result of `curl -I https://registry.k8s.io/v2/manifests/pause/tags/list` : timeout

**Comment by chhsiao1981** [comment]
I checked again from Boston:
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/2970164/205399963-154b42aa-6ebf-4827-8ff5-a2b73628c7df.png">

and I checked again with europe-west8 from Uganda:

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/2970164/205400062-25545de3-30ce-44cc-8b7f-b6bdfd5f2548.png">

but result of `curl -I https://registry.k8s.io/v2/manifests/pause/tags/list` is still timeout from Uganda.

**Comment by chhsiao1981** [comment]
I would assume that some network configuration from our side blocked `registry.k8s.io` for now.
