### ISSUE TITLE
why kubernetes images url format is `<registry_url>/<image_name>:<image_tag>`

### ISSUE THREAD

**Issue by willzhang** [kubernetes/registry.k8s.io#139]
## what happend
here is kubespray images.list , and generate by [manage-offline-container-images.sh](https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/offline/manage-offline-container-images.sh)
```
$ cat temp/images.list |grep registry.k8s.io
registry.k8s.io/pause:3.7
registry.k8s.io/coredns/coredns:v1.9.3
registry.k8s.io/dns/k8s-dns-node-cache:1.21.1
registry.k8s.io/cpa/cluster-proportional-autoscaler-amd64:1.8.5
registry.k8s.io/metrics-server/metrics-server:v0.6.2
registry.k8s.io/sig-storage/local-volume-provisioner:v2.5.0
registry.k8s.io/ingress-nginx/controller:v1.5.1
registry.k8s.io/sig-storage/csi-attacher:v3.3.0
registry.k8s.io/sig-storage/csi-provisioner:v3.0.0
registry.k8s.io/sig-storage/csi-snapshotter:v5.0.0
registry.k8s.io/sig-storage/snapshot-controller:v4.2.1
registry.k8s.io/sig-storage/csi-resizer:v1.3.0
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.4.0
registry.k8s.io/kube-apiserver:v1.25.5
registry.k8s.io/kube-controller-manager:v1.25.5
registry.k8s.io/kube-scheduler:v1.25.5
registry.k8s.io/kube-proxy:v1.25.5
```
why only kubernetes images url format is `<registry_url>/<image_name>:<image_tag>`
```
$ cat temp/images.list |grep registry.k8s.io/kube
registry.k8s.io/kube-apiserver:v1.25.5
registry.k8s.io/kube-controller-manager:v1.25.5
registry.k8s.io/kube-scheduler:v1.25.5
registry.k8s.io/kube-proxy:v1.25.5

$ cat temp/images.list |grep registry.k8s.io/pause
registry.k8s.io/pause:3.7
```

i don't know why container images can have two format, but I think Kubernetes image should also comply with the common image address standard---format2.

```
format1: <registry_url>/<image_name>:<image_tag>

format2: <registry_url>/<project_name>/<image_name>:<image_tag>
```

## kubespray offline design

in offline environment, kubespray let user use a local registry url with `kube_image_repo: "{{ registry_host }}"`  variable

![image](https://user-images.githubusercontent.com/33590311/212522327-a55baaa7-9118-40e7-8a4c-c8f4b9cd95cc.png)

However, because the kubernetes image uses a chaotic image format, it is difficult to align：

![image](https://user-images.githubusercontent.com/33590311/212522457-8f20f8a2-5b26-4640-a999-5046572da83e.png)

eg : i can't config `kube_image_repo: "192.168.72.16"`, if i push `registry.k8s.io/pause:3.7-->192.168.72.16/kube/pause:3.7`（harbor）, Kubeadm will not find this image address, it only find `192.168.72.16/pause:3.7`

## what the problems

when i want push all images to offline harbor registry, This mix of image lists in different formats can lead to confusion， and it's hard  for push shell scripts to Handle this situation.

and final it cause me must use docker registry (registry:2), because harbor only support format2.

## suggest

```
registry.k8s.io/kube/pause:3.7
registry.k8s.io/kube/kube-apiserver:v1.25.5
registry.k8s.io/kube/kube-controller-manager:v1.25.5
registry.k8s.io/kube/kube-scheduler:v1.25.5
registry.k8s.io/kube/kube-proxy:v1.25.5
```

**Comment by neolit123** [comment]
> and final it cause me must use docker registry (registry:2), because harbor only support format2.

that sounds like a missing flexibility in harbor.

> suggest

it does make sense to have the subpath consistency, but we cannot just move the images to the new location.
they likely have to be mirrored first, and if we decide to migrate users to the new location it will be a long process.

> kubespray offline design

kubespray uses kubeadm and kubeadm's imageRepositry API field can technically accept a "repo/path" format and not only "repo". the problem will be with coredns images that will become "repo/path/coredns" which will not be valid unless you pushed coredns to that path instead of "repo/coredns". the kubeadm API has individual field for DNS that can be used to override the coredns image path, though.

**Comment by willzhang** [comment]
- that sounds like a missing flexibility in harbor.
yes ,but i think harbor will not support push image without project name, it have a web ui to list and manage all projects, no project name will  cause the ui list to become confused.

- it does make sense to have the subpath consistency

there just have 6 images use short format, and only k8s have this short format ,hope have a change in furture
```
root@node51:~# kubeadm config images list
I0117 09:21:50.999039 1387839 version.go:256] remote version is much newer: v1.26.0; falling back to: stable-1.25
registry.k8s.io/kube-apiserver:v1.25.5
registry.k8s.io/kube-controller-manager:v1.25.5
registry.k8s.io/kube-scheduler:v1.25.5
registry.k8s.io/kube-proxy:v1.25.5
registry.k8s.io/pause:3.8
registry.k8s.io/etcd:3.5.6-0
registry.k8s.io/coredns/coredns:v1.9.3
```

- kubespray uses kubeadm and kubeadm's imageRepositry 

yes ,So this is the problem caused by inconsistency

**Comment by BenTheElder** [comment]
Those 6 images are available in two formats, however this is not up to registry.k8s.io, it's up to SIG release publishing them in the backing store.

Harbor should fix this, because it's fully in compliance with OCI distribution to just have `host/image:tag` AFAIK, and Kubernetes has been doing this a _long_ time. registry.k8s.io has the exact same image names as k8s.gcr.io, by design.

**Comment by BenTheElder** [comment]
FYI @kubernetes/sig-release @kubernetes/release-engineering 

Kubernetes does not currently plan to remove the short format for consistency reasons, it has been around a _long_ time.

You could file a bug with kubernetes/release and kubernetes/kubeadm to ask the respective projects to switch to only the nested format, but it will remain for all existing Kubernetes minor versions, and registry.k8s.io infrastructure will remain unchanged.
