### ISSUE TITLE
make registry.k8s.io reusable

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/registry.k8s.io#152]
Right now we've hardcoded some things to prioritize shipping an efficient implementation expediently.

In particular the AWS client region : backend bucket mapping is hardcoded in the application, to avoid complex runtime config loading in cloud run, simplifying the app and improving reliability but making the cmd/archeio non-reusable.

However, since we started, some key things have changed:

1. We stopped using k8s.gcr.io to regionalize backend traffic for us, in order to migrate to Artifact Registry regional instances and unblock the possibility of redirecting k8s.gcr.io to registry.k8s.io. In doing so we configured each cloud run region to forward traffic to a matching Artifact Registry region, leaning on the application loadbalancer (GCLB) in front of the regional backend instances to determine which region we should serve from.
2. We have substantial funding from AWS, instead of a verbal agreement to host AWS client traffic specifically
3. Due to 1) and 2) we implemented #147 which was done by configuring a mapping from cloud run region to default S3 bucket, based on region proximity between GCP and AWS.

As a result, except for known-AWS client IPs, we already map based on the location of the application instance receiving the traffic behind the loadbalancer, which appears to be working well so far. We're also not as sensitive to spend on AWS with increased funding.

This has been discussed before, but I propose ripping out the hardcoded bucket mapping and instead allow a simple environment variable configuration like this:
```
GCP_LAYER_HOST=upstream
AWS_LAYER_HOST=https://s3-bucket-for-instance-region
```

Where for each `${CLOUD}_LAYER_HOST` environment variable we allow either "upstream" (meaning the source registry) or `"http...."` (meaning some object store).

Then other potential users can use the same binary/image as us and just configure these inputs differently.

The upstream source registry is already configurable, and the only thing we depend on there is public-read-without-authentication.

There will be a cost increase for us as we less-precisely map to the nearest S3 backend, but I don't expect that to be an issue anymore with the updated funding. In return this will be even simpler to maintain, as we need only configure the cloud run instances with the default backend per cloud we support detecting. That mapping can be updated without touching the binary sources and still avoid complex runtime config (and potential operational issues with config parsing failures, slower app warmup, etc).

Future clouds will be straightforward to add.

**Comment by ameukam** [comment]
+1

**Comment by BenTheElder** [comment]
If/when we do this, we should expand IP data to region-less provider data, like cloud.json => goog.json.

**Comment by BenTheElder** [comment]
Actually, thinking more about this: I don't think this needs to happen.

So far we've only had 1-2 requests, I think relatively few projects will find themselves in this situation.

If they do, this is relatively easy to build even just configuring something like nginx, and we should focus on what Kubernetes needs (e.g. also things like serving LF privacy policy) and not worry about making this more complex to serve other projects.

If serving public-read images split across multiple providers actually became a very common need, we could engage in collaborating with other projects, but currently there just isn't much demand.
