### ISSUE TITLE
Proposal: add a Cloudflare R2 mirror

### ISSUE THREAD

**Issue by imjasonh** [kubernetes/registry.k8s.io#157]
## What

[Cloudflare R2](https://www.cloudflare.com/products/r2/) is a relatively new S3-API-compatible blob storage service from Cloudflare, that boasts _free egress_, unlike GCS and AWS S3.

I wanted to open this issue to discuss the possibility, advantages/disadvantages of, and to gauge interest in adding R2 as a backend for registry.k8s.io, in addition to the current GCS (upstream) and S3 backends.

Based on interest, benefits, etc., I may be willing to volunteer some cycles to make this happen.

## Why

This project has done a lot of work to be able to serve blobs to AWS customers using blobs already in AWS, to avoid cross-cloud latency and egress costs from GCP. Folks pulling images from GCP already get the locality and cost benefit.

Users outside those two clouds fallback to pulling from GCP, which is probably totally fine for speed, but still incurs egress cost on the project. How much that costs, I don't know.

By adding an R2 mirror, we can further lower the egress cost burden on the project for pullers from around the internet, and from other clouds.

## How (...roughly)

Based on a quick reading of the code, it looks like it should be possible to add a third check (after GCS and S3) here:

https://github.com/kubernetes/registry.k8s.io/blob/619f45bb02ed7ec93dfb3894c81ac3e18bcd1160/cmd/archeio/app/handlers.go#L133

...that checks if the blob is available in R2, and if so redirects to it, just like with S3.

[geranos' S3 uploader](https://github.com/kubernetes/registry.k8s.io/blob/619f45bb02ed7ec93dfb3894c81ac3e18bcd1160/cmd/geranos/s3uploader.go) should likewise be able to be pointed to R2 without many serious changes.

I believe that [existing Terraform to configure S3 for registry.k8s.io](https://github.com/kubernetes/k8s.io/tree/main/infra/aws/terraform/registry.k8s.io) should be able to be reusable to provision and configure R2 buckets. [R2's Terraform example](https://developers.cloudflare.com/r2/examples/terraform/) uses the S3 Terraform provider directly, and just points its API endpoint to R2 instead of S3, since both APIs are compatible.

Unlike S3, there is no regionality to an R2 bucket. Instead, the region is `"auto"`, and R2 serves bits from wherever it can across its global network. More details on this are light in the docs, unfortunately.

## Links

- S3 compatibility status: https://developers.cloudflare.com/r2/data-access/s3-api/api/
- Pricing: https://developers.cloudflare.com/r2/platform/pricing/
- R2 Public Buckets: https://developers.cloudflare.com/r2/data-access/public-buckets/
- https://blog.cloudflare.com/aws-egregious-egress/

**Comment by BenTheElder** [comment]
[Sorry nobody else got to this yet and I was on vacation last week]

This is an interesting thought, it's worth noting that we now have a new _large_ ($3M/year for 2023+) and relatively unused budget for AWS. So spending on AWS is not an immediate concern. At the moment we're focused on:

- Driving traffic away from k8s.gcr.io
- Eliminating the dependency on GCR's GCS bucket (geranos)
- Cutting costs in other parts of Kubernetes' infrastructure (like binary downloads https://github.com/kubernetes-sigs/porche)

**Comment by BenTheElder** [comment]
discussed some more with jason, I think we're not pursuing this for now for various reasons, including at the moment the organization has chosen to use other CDN providers

Forgot to clarify this as well though:
> Users outside those two clouds fallback to pulling from GCP, which is probably totally fine for speed, but still incurs egress cost on the project. How much that costs, I don't know.

Actually, they fallback on AWS/S3 now, now that we have a real budget from Amazon, and so far it looks very manageable. #147 
cloudfront is also on the table for future iterations.

**Comment by imjasonh** [comment]
Thanks for your response! (Sorry I didn't respond myself sooner)

It makes total sense to rely on the existing cloud credits you have. If the details of these arrangements ever change in any seriously material way, let me know and I'll be happy to contribute to an R2 mirror, but until then, it sounds like you're all set. 👍
