### ISSUE TITLE
Expand AR and Cloud Run Regions

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/registry.k8s.io#236]
We're in 20 regions*

* 19 fully deployed at the moment following https://github.com/kubernetes/registry.k8s.io/issues/234

We should evaluate expanding to remaining regions, further reducing the blast radius for issues like #234 and continuing to benefit at the cost trade-off of storage << bandwidth for any remaining regions where this is true.

IIRC @upodroid already had a PR related to this, but we held off primarily due to #181 and image promoter concerns.

We've had some work on the promoter since then, and I'm not sure if we have any remaining blockers to add a few more regions to further improve isolation and capacity.

cc @puerco @ameukam

**Comment by ameukam** [comment]
Related to:
- #172 

For the promoter we are covering all the AR regions except the newest (open less than 2 months ago).

**Comment by BenTheElder** [comment]
> For the promoter we are covering all the AR regions except the newest (open less than 2 months ago).

TIL! I could've sworn we had another discussion to add AR regions that we held off, I must be mis-remembering

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/k8s.io/pull/4949 related, we added two regions here that don't seem to be promoted to yet

**Comment by BenTheElder** [comment]
I was thinking of this thread https://github.com/kubernetes/release/issues/2947#issuecomment-1458412293

**Comment by BenTheElder** [comment]
With the registry freeze in effect, promoter improvements, and the redirect settled, I think we can revisit https://github.com/kubernetes/release/issues/2947#issuecomment-1458412293 and add a few regions relatively fine.

Once those are live we can easily spin up additional cloud run regions pointed at them.

**Comment by ameukam** [comment]
We extended registry.k8s.io:
- europe-west10
- europe-west3

**Comment by BenTheElder** [comment]
I'm not sure the promoter can handle this and we seem to be doing well for the moment with the current set.
