### ISSUE TITLE
Firewall rules for pulling images

### ISSUE THREAD

**Issue by dev-nimbeo** [kubernetes/registry.k8s.io#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

Hi,

We need to pull images from kubernetes cluster behind a firewall proxy. What are the address we should whitelisting for allowing access to registry.k8s.io? Which ports? Just 443? Or 80 is also needed?

Thank you

### Debugging Information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TerryHowe** [comment]
It depends on where you are pulling from AND what IP, but nothing should be pulled over 80, just 443. If you were pulling from GCP, you would get GCP servers and AWS would give you AWS servers.

You can for example:

```
oras pull -v -d --platform amd64 registry.k8s.io/cluster-api-nested/cluster-api-nested-controller:v0.1.0 2>&1 | grep 'Request URL'
```

To get a list of the domains. For me for example:
```
> Request URL: "https://registry.k8s.io/v2/cluster-api-nested/cluster-api-nested-controller/manifests/v0.1.0"
> Request URL: "https://us-west1-docker.pkg.dev/v2/k8s-artifacts-prod/images/cluster-api-nested/cluster-api-nested-controller/manifests/v0.1.0"
```

**Comment by BenTheElder** [comment]
We don't support a stable list of domains, you should mirror. 

https://github.com/kubernetes/registry.k8s.io#stability
