### ISSUE TITLE
Can't pull images from registry.k8s.io on EKS nodes on AWS in af-south-1

### ISSUE THREAD

**Issue by Th3NightHawk** [kubernetes/registry.k8s.io#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

When trying to pull any images from registry.k8s.io on an EKS node running in AWS in af-south-1 we get the below errors:
```
error="failed to do request: Head \"https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9\": EOF" host=registry.k8s.io
ctr: failed to resolve reference "registry.k8s.io/pause:3.9": failed to do request: Head "https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9": EOF
```
If I try to get that manifest file using wget directly I get a SSL handshake failure (not sure if this is expected):
```
# wget https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 -d
DEBUG output created by Wget 1.14 on linux-gnu.

URI encoding = ‘UTF-8’
Converted file name '3.9' (UTF-8) -> '3.9' (UTF-8)
Converted file name '3.9' (UTF-8) -> '3.9' (UTF-8)
--2023-07-20 11:08:35--  https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
Resolving europe-west8-docker.pkg.dev (europe-west8-docker.pkg.dev)... 66.102.1.82, 2a00:1450:400c:c00::52
Caching europe-west8-docker.pkg.dev => 66.102.1.82 2a00:1450:400c:c00::52
Connecting to europe-west8-docker.pkg.dev (europe-west8-docker.pkg.dev)|66.102.1.82|:443... connected.
Created socket 3.
Releasing 0x0000000000afef40 (new refcount 1).
Initiating SSL handshake.
SSL handshake failed.
Closed fd 3
Unable to establish SSL connection.
```
When testing this from a node running in eu-west-1 we don't encounter this issue (looks like those requests get redirected to europe-west2-docker.pkg.dev)

### Debugging Information

# curl -v https://registry.k8s.io/v2/
*   Trying 34.96.108.209:443...
* Connected to registry.k8s.io (34.96.108.209) port 443 (#0)
* ALPN: offers h2,http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=registry.k8s.io
*  start date: Jul  8 04:12:31 2023 GMT
*  expire date: Oct  6 05:08:26 2023 GMT
*  subjectAltName: host "registry.k8s.io" matched cert's "registry.k8s.io"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /v2/]
* h2h3 [:scheme: https]
* h2h3 [:authority: registry.k8s.io]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x102e6c0)
> GET /v2/ HTTP/2
> Host: registry.k8s.io
> user-agent: curl/7.88.1
> accept: */*
>
< HTTP/2 200
< docker-distribution-api-version: registry/2.0
< x-cloud-trace-context: 020b84781542457f76c96ad7605ae753
< date: Thu, 20 Jul 2023 10:51:44 GMT
< content-type: text/html
< server: Google Frontend
< content-length: 0
< via: 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
* Connection #0 to host registry.k8s.io left intact

# crane ls registry.k8s.io/pause
2023/07/20 10:51:45 retrying EOF
2023/07/20 10:51:45 retrying EOF
2023/07/20 10:51:46 retrying EOF
Error: reading tags for registry.k8s.io/pause: Get "https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/tags/list": EOF

# crane pull --verbose registry.k8s.io/pause:3.9 pause.tgz
2023/07/20 10:51:46 --> GET https://registry.k8s.io/v2/
2023/07/20 10:51:46 GET /v2/ HTTP/1.1
Host: registry.k8s.io
User-Agent: crane/0.15.2 go-containerregistry/0.15.2
Accept-Encoding: gzip

2023/07/20 10:51:47 <-- 200 https://registry.k8s.io/v2/ (1.103254078s)
2023/07/20 10:51:47 HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html
Date: Thu, 20 Jul 2023 10:51:47 GMT
Docker-Distribution-Api-Version: registry/2.0
Server: Google Frontend
Via: 1.1 google
X-Cloud-Trace-Context: a1b8c59ee65303801edbf2608a050e85
Content-Length: 0

2023/07/20 10:51:47 --> GET https://registry.k8s.io/v2/pause/manifests/3.9
2023/07/20 10:51:47 GET /v2/pause/manifests/3.9 HTTP/1.1
Host: registry.k8s.io
User-Agent: crane/0.15.2 go-containerregistry/0.15.2
Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json
Accept-Encoding: gzip

2023/07/20 10:51:47 <-- 307 https://registry.k8s.io/v2/pause/manifests/3.9 (240.355443ms)
2023/07/20 10:51:47 HTTP/2.0 307 Temporary Redirect
Content-Length: 120
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=utf-8
Date: Thu, 20 Jul 2023 10:51:47 GMT
Location: https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
Server: Google Frontend
Via: 1.1 google
X-Cloud-Trace-Context: 8089b440f9e2c3a6eb732ba3b1e76e71

<a href="https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9">Temporary Redirect</a>.

2023/07/20 10:51:47 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:47 GET /v2/k8s-artifacts-prod/images/pause/manifests/3.9 HTTP/1.1
Host: europe-west8-docker.pkg.dev
User-Agent: crane/0.15.2 go-containerregistry/0.15.2
Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json
Referer: https://registry.k8s.io/v2/pause/manifests/3.9
Accept-Encoding: gzip

2023/07/20 10:51:47 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (14.84509ms)
2023/07/20 10:51:47 retrying EOF
2023/07/20 10:51:47 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:47 GET /v2/k8s-artifacts-prod/images/pause/manifests/3.9 HTTP/1.1
Host: europe-west8-docker.pkg.dev
User-Agent: crane/0.15.2 go-containerregistry/0.15.2
Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json
Referer: https://registry.k8s.io/v2/pause/manifests/3.9
Accept-Encoding: gzip

2023/07/20 10:51:47 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (14.918772ms)
2023/07/20 10:51:47 retrying EOF
2023/07/20 10:51:48 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:48 GET /v2/k8s-artifacts-prod/images/pause/manifests/3.9 HTTP/1.1
Host: europe-west8-docker.pkg.dev
User-Agent: crane/0.15.2 go-containerregistry/0.15.2
Accept: application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.v1+prettyjws,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json
Referer: https://registry.k8s.io/v2/pause/manifests/3.9
Accept-Encoding: gzip

2023/07/20 10:51:48 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (9.577469ms)
2023/07/20 10:51:48 retrying EOF
Error: Get "https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9": EOF

# crane pull --verbose registry.k8s.io/pause:3.9 pause.tgz 2>&1 | grep 'GET https'
2023/07/20 10:51:49 --> GET https://registry.k8s.io/v2/
2023/07/20 10:51:50 --> GET https://registry.k8s.io/v2/pause/manifests/3.9
2023/07/20 10:51:50 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:50 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (15.565455ms)
2023/07/20 10:51:50 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:50 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (14.964643ms)
2023/07/20 10:51:50 --> GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
2023/07/20 10:51:50 <-- EOF GET https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 (12.568291ms)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Th3NightHawk** [comment]
I have also tested pulling the manifest from the registry used by nodes in eu-west-1 from a node running in af-south-1 and that worked without any errors:
```
# wget https://europe-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9 -d
DEBUG output created by Wget 1.14 on linux-gnu.

URI encoding = ‘UTF-8’
Converted file name '3.9' (UTF-8) -> '3.9' (UTF-8)
Converted file name '3.9' (UTF-8) -> '3.9' (UTF-8)
--2023-07-20 11:20:50--  https://europe-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.9
Resolving europe-west2-docker.pkg.dev (europe-west2-docker.pkg.dev)... 108.177.15.82, 2a00:1450:400c:c0c::52
Caching europe-west2-docker.pkg.dev => 108.177.15.82 2a00:1450:400c:c0c::52
Connecting to europe-west2-docker.pkg.dev (europe-west2-docker.pkg.dev)|108.177.15.82|:443... connected.
Created socket 3.
Releasing 0x00000000020b1f40 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00000000020fd3b0
certificate:
  subject: /CN=*.googlecode.com
  issuer:  /C=US/O=Google Trust Services LLC/CN=GTS CA 1C3
X509 certificate successfully verified and matches host europe-west2-docker.pkg.dev

---request begin---
GET /v2/k8s-artifacts-prod/images/pause/manifests/3.9 HTTP/1.1
User-Agent: Wget/1.14 (linux-gnu)
Accept: */*
Host: europe-west2-docker.pkg.dev
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 200 OK
Content-Length: 2405
Content-Type: application/vnd.docker.distribution.manifest.list.v2+json
Docker-Content-Digest: sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0
Date: Thu, 20 Jul 2023 11:20:52 GMT
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: 2405 (2.3K) [application/vnd.docker.distribution.manifest.list.v2+json]
Saving to: ‘3.9.1’

100%[================================================================================================================================================================================================================================================>] 2,405       --.-K/s   in 0s

2023-07-20 11:20:52 (51.3 MB/s) - ‘3.9.1’ saved [2405/2405]
```

**Comment by BenTheElder** [comment]
I don't think we can do much about pkg.dev SSL 🤔

**Comment by mrbobbytables** [comment]
As there hasn't been anything further on this in several months, I am going to go ahead and close it out. 👍 Please reopen should it need further discussion.

**Comment by AndrewMullin01** [comment]
I am facing the same problem in af-south-1.

`docker pull registry.k8s.io/metrics-server/metrics-server:v0.6.41` results in:

> Error response from daemon: Head "https://europe-west8-docker.pkg.dev/v2/k8s-artifacts-prod/images/metrics-server/metrics-server/manifests/v0.6.4": EOF

I can `wget` https://europe-**west1**-docker.pkg.dev, but not https://europe-**west8**-docker.pkg.dev
```
$ wget https://europe-west8-docker.pkg.dev
--2023-10-17 10:08:19--  https://europe-west8-docker.pkg.dev/
Resolving europe-west8-docker.pkg.dev (europe-west8-docker.pkg.dev)... 173.194.76.82, 2a00:1450:400c:c03::52
Connecting to europe-west8-docker.pkg.dev (europe-west8-docker.pkg.dev)|173.194.76.82|:443... connected.
GnuTLS: The TLS connection was non-properly terminated.
Unable to establish SSL connection.
```

Any suggestions welcome. Will try @ameukam's pull-through cache solution in the meantime.

**Comment by AndrewMullin01** [comment]
Can confirm ECR pull through cache to be a working solution 👍

**Comment by Th3NightHawk** [comment]
> Can confirm ECR pull through cache to be a working solution 👍 

I wouldn't call it a solution, it's a workaround. The solution would be to fix the cert on the host.

**Comment by dims** [comment]
@Th3NightHawk the correct solution ... is for everyone to setup their own mirrors for their production workloads and NOT waste community's limited resources

**Comment by Th3NightHawk** [comment]
> @Th3NightHawk the correct solution ... is for everyone to setup their own mirrors for their production workloads and NOT waste community's limited resources

I completely agree! We setup a Harbor instance in af-south-1 to pull and cache the images however we are unable to do so because of that error.

**Comment by dims** [comment]
thank you much appreciated @Th3NightHawk

**Comment by wormza** [comment]
> @Th3NightHawk the correct solution ... is for everyone to setup their own mirrors for their production workloads and NOT waste community's limited resources

The issue is not specific to production workloads though. Anything from af-south-1 doesn't work. So even as a community user just trying to play with k8s in my personal, account I get issues.

Having to use a work-around is doable, but not ideal.
