### ISSUE TITLE
Not able to install K8s Cluster using kubeadm init command due to x509: certificate signed by unknown authority.

### ISSUE THREAD

**Issue by lokesh090909** [kubernetes/registry.k8s.io#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

while running kubeadm init, K8s command is should able to pull images from repository.

### Debugging Information

root@k8s-master:/etc/kubernetes# kubeadm init --pod-network-cidr 10.10.0.0/16 --kubernetes-version 1.28.2 --node-name k8s-master --v=5
I0929 12:19:32.619343 32227 initconfiguration.go:117] detected and using CRI socket: unix:///var/run/containerd/containerd.sock
I0929 12:19:32.620338 32227 interface.go:432] Looking for default routes with IPv4 addresses
I0929 12:19:32.620360 32227 interface.go:437] Default route transits interface "ens33"
I0929 12:19:32.620507 32227 interface.go:209] Interface ens33 is up
I0929 12:19:32.620572 32227 interface.go:257] Interface "ens33" has 2 addresses :[10.237.X.X/24 fe80::250:56ff:fe89:9917/64].
I0929 12:19:32.620602 32227 interface.go:224] Checking addr 10.237.X.X/24.
I0929 12:19:32.620615 32227 interface.go:231] IP found 10.237.X.X
I0929 12:19:32.620652 32227 interface.go:263] Found valid IPv4 address 10.237.X.X for interface "ens33".
I0929 12:19:32.620667 32227 interface.go:443] Found active IP 10.237.X.X
I0929 12:19:32.620693 32227 kubelet.go:196] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
[init] Using Kubernetes version: v1.28.2
[preflight] Running pre-flight checks
I0929 12:19:32.625498 32227 checks.go:563] validating Kubernetes and kubeadm version
I0929 12:19:32.625546 32227 checks.go:168] validating if the firewall is enabled and active
I0929 12:19:32.632968 32227 checks.go:203] validating availability of port 6443
I0929 12:19:32.633168 32227 checks.go:203] validating availability of port 10259
I0929 12:19:32.633212 32227 checks.go:203] validating availability of port 10257
I0929 12:19:32.633250 32227 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0929 12:19:32.633270 32227 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0929 12:19:32.633286 32227 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0929 12:19:32.633302 32227 checks.go:280] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0929 12:19:32.633314 32227 checks.go:430] validating if the connectivity type is via proxy or direct
I0929 12:19:32.633351 32227 checks.go:469] validating http connectivity to first IP address in the CIDR
I0929 12:19:32.633375 32227 checks.go:469] validating http connectivity to first IP address in the CIDR
I0929 12:19:32.633398 32227 checks.go:104] validating the container runtime
I0929 12:19:32.654782 32227 checks.go:639] validating whether swap is enabled or not
I0929 12:19:32.654873 32227 checks.go:370] validating the presence of executable crictl
I0929 12:19:32.654927 32227 checks.go:370] validating the presence of executable conntrack
I0929 12:19:32.654960 32227 checks.go:370] validating the presence of executable ip
I0929 12:19:32.654983 32227 checks.go:370] validating the presence of executable iptables
I0929 12:19:32.655015 32227 checks.go:370] validating the presence of executable mount
I0929 12:19:32.655038 32227 checks.go:370] validating the presence of executable nsenter
I0929 12:19:32.655060 32227 checks.go:370] validating the presence of executable ebtables
I0929 12:19:32.655088 32227 checks.go:370] validating the presence of executable ethtool
I0929 12:19:32.655112 32227 checks.go:370] validating the presence of executable socat
I0929 12:19:32.655136 32227 checks.go:370] validating the presence of executable tc
I0929 12:19:32.655165 32227 checks.go:370] validating the presence of executable touch
I0929 12:19:32.655189 32227 checks.go:516] running all checks
I0929 12:19:32.666397 32227 checks.go:401] checking whether the given node name is valid and reachable using net.LookupHost
I0929 12:19:32.666591 32227 checks.go:605] validating kubelet version
I0929 12:19:32.716982 32227 checks.go:130] validating if the "kubelet" service is enabled and active
I0929 12:19:32.726471 32227 checks.go:203] validating availability of port 10250
I0929 12:19:32.726540 32227 checks.go:329] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0929 12:19:32.726587 32227 checks.go:329] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0929 12:19:32.726625 32227 checks.go:203] validating availability of port 2379
I0929 12:19:32.726660 32227 checks.go:203] validating availability of port 2380
I0929 12:19:32.726683 32227 checks.go:243] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0929 12:19:32.726790 32227 checks.go:828] using image pull policy: IfNotPresent
I0929 12:19:32.747684 32227 checks.go:854] pulling: registry.k8s.io/kube-apiserver:v1.28.2
I0929 12:19:33.483094 32227 checks.go:854] pulling: registry.k8s.io/kube-controller-manager:v1.28.2
I0929 12:19:34.243051 32227 checks.go:854] pulling: registry.k8s.io/kube-scheduler:v1.28.2
I0929 12:19:34.994940 32227 checks.go:854] pulling: registry.k8s.io/kube-proxy:v1.28.2
W0929 12:19:35.768775 32227 checks.go:835] detected that the sandbox image "registry.k8s.io/pause:3.6" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.k8s.io/pause:3.9" as the CRI sandbox image.
I0929 12:19:35.789048 32227 checks.go:854] pulling: registry.k8s.io/pause:3.9
I0929 12:19:36.551551 32227 checks.go:854] pulling: registry.k8s.io/etcd:3.5.9-0
I0929 12:19:37.346778 32227 checks.go:854] pulling: registry.k8s.io/coredns/coredns:v1.10.1
[preflight] Some fatal errors occurred:
[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.28.2: output: E0929 12:19:33.460196 32316 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/kube-apiserver:v1.28.2": failed to resolve reference "registry.k8s.io/kube-apiserver:v1.28.2": failed to do request: Head "[https://us-east4-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.2\](https://us-east4-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.2%5C)": x509: certificate signed by unknown authority" image="registry.k8s.io/kube-apiserver:v1.28.2"
time="2023-09-29T12:19:33Z" level=fatal msg="pulling image: failed to pull and unpack image "registry.k8s.io/kube-apiserver:v1.28.2": failed to resolve reference "registry.k8s.io/kube-apiserver:v1.28.2": failed to do request: Head "[https://us-east4-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.2\](https://us-east4-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.2%5C)": x509: certificate signed by unknown authority"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
cmd/kubeadm/app/cmd/phases/workflow/runner.go:260
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
cmd/kubeadm/app/cmd/init.go:111
github.com/spf13/cobra.(*Command).execute
vendor/github.com/spf13/cobra/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
vendor/github.com/spf13/cobra/command.go:1068
github.com/spf13/cobra.(*Command).Execute
vendor/github.com/spf13/cobra/command.go:992
k8s.io/kubernetes/cmd/kubeadm/app.Run
cmd/kubeadm/app/kubeadm.go:50
main.main
cmd/kubeadm/kubeadm.go:25
runtime.main
/usr/local/go/src/runtime/proc.go:250
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1598

### Anything else?

Environment:
Cloud provider or hardware configuration: VMware
OS (e.g: cat /etc/os-release): Ubuntu 22.04.3 LTS
Kernel (e.g. uname -a):Linux k8s-master 5.15.0-84-generic https://github.com/kubernetes/release/pull/93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ameukam** [comment]
Not feedback since the last comment. Closing. 
/close
