### ISSUE TITLE
kubeadm init clone project to local compilation error

### ISSUE THREAD

**Issue by devbiu** [kubernetes/registry.k8s.io#266]
### What happened?

download kubernetes-1.24.17.tar.gz to local environment
use commond 
```shell 
KUBE_BUILD_PLATFORMS=linux/amd64 make all GOFLAGS=-v GOGCFLAGS="-N -l" 
```
compile
kubeadm config images list view require images as follow
<img width="606" alt="image" src="https://github.com/kubernetes/kubernetes/assets/99388822/445e4d8d-62ad-4961-92c0-87e575c4dee9">
because only the tag in the docker is 1.24.17 image， use the tag command to modify the tag of the image
<img width="927" alt="image" src="https://github.com/kubernetes/kubernetes/assets/99388822/799f9aa9-cc77-4a3f-9c78-b75791b0b3eb">
enable corresponding images and tags

subsequent execution commond 
```shell 
kubeadm init
```
alter still asks me to pull images 
<img width="1398" alt="image" src="https://github.com/kubernetes/kubernetes/assets/99388822/765c5a0f-3670-42bf-8c96-cc3c36174b51">

### What did you expect to happen?

kubernetes install success 

### How can we reproduce it (as minimally and precisely as possible)?

```shell 
KUBE_BUILD_PLATFORMS=linux/amd64 make all GOFLAGS=-v GOGCFLAGS="-N -l" 
kubeadm init
```

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.17", GitCommit:"22a9682c8fe855c321be75c5faacde343f909b04", GitTreeState:"clean", BuildDate:"2023-10-16T11:32:47Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
red Hat Linux
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# red Hat Enterprise Linux release 8.3
$ uname -a
# Linux xxxxx  x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
It looks like your local DNS server is refusing requests?

**Comment by devbiu** [comment]
> It looks like your local DNS server is refusing requests?

because the local network cannot connect to the Internet

So I imported the required image in advance so that it cannot be downloaded remotely

and using image pull policy IfNotPresent 

So should I no longer pull images from remote locations?

**Comment by neolit123** [comment]
> So I imported the required image in advance so that it cannot be downloaded remotely

did you import them in the k8s.io namespace?

**Comment by devbiu** [comment]
> > So I imported the required image in advance so that it cannot be downloaded remotely
> 
> did you import them in the k8s.io namespace?

This is okay for me
I mistakenly understood that the runtime of kubadm is docker, but the actual runtime is containerd.
So after I imported the image into the k8s namespace k8s.io through ctr, modified its tag through the command
as follows
<img width="1328" alt="image" src="https://github.com/kubernetes/registry.k8s.io/assets/99388822/da265242-a481-46c2-bd0e-0537eae811bf">

 I re-executed 
```shell
kubaadm init --v=5 
```
and was able to find the image.

Thank you for your answer

**Comment by devbiu** [comment]
What puzzles me is why the runtime is containerd instead of docker. As far as I know, lower versions of kubernetes import the image into docker instead of ctr. Can you explain it to me?

**Comment by neolit123** [comment]
> What puzzles me is why the runtime is containerd instead of docker. As far as I know, lower versions of kubernetes import the image into docker instead of ctr. Can you explain it to me?

docker is no longer supported by default by kubeadm and core kubernetes. there is a new container runtime "shim" called cri-dockerd that is needed.
if you used `kubeadm config images pull ...`, then kubeadm would use `crictl` to download the images in the container runtime it found. probably in your case it only found the containerd socket.

closing as not a bug
/close
