### ISSUE TITLE
Unable to pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.2

### ISSUE THREAD

**Issue by adarsh-dell** [kubernetes/registry.k8s.io#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

We should be able to pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.2

### Debugging Information

![image](https://github.com/kubernetes/registry.k8s.io/assets/109620911/49b13f50-cb89-4603-9c60-01213a964dac)

### Anything else?

While I am able to pull v2.9.1
![image](https://github.com/kubernetes/registry.k8s.io/assets/109620911/49b13f50-cb89-4603-9c60-01213a964dac)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ameukam** [comment]
There is no image for `2.9.2`. Is there any expectation that the tag should be published ? If that's the case, please reach out the maintainers of this component.

**Comment by adarsh-dell** [comment]
> There is no image for `2.9.2`. Is there any expectation that the tag should be published ? If that's the case, please reach out the maintainers of this component.

https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.9.2
![image](https://github.com/kubernetes/registry.k8s.io/assets/109620911/3e943cde-5551-4b8e-b4d6-49640e6d2ee6)

**Comment by adarsh-dell** [comment]
Hello @ameukam, do you have any updates or assistance to offer regarding this issue? Could you please provide me with the registry link so that I can view the available tags?

**Comment by BenTheElder** [comment]
We don't support browsing, and the specific project needs to ensure they're publishing images correctly.

registry.k8s.io/sig-storage/csi-node-driver-registrar Is not configured with a 2.9.2 tag, there are links in the README to the tooling the project uses for publication and configuration.

https://github.com/kubernetes/k8s.io/blob/1d3af95c11edcaccf05c9b0840af66510057d6fd/registry.k8s.io/images/k8s-staging-sig-storage/images.yaml#L57

https://github.com/kubernetes-csi/node-driver-registrar/issues/359 Is a better tracking issue
/close
