### ISSUE TITLE
Error response from daemon: Head "https://europe-west3-docker.pkg.dev/v2/k8s-artifacts-prod/images/sig-storage/csi-provisioner/manifests/v4.0.0": Forbidden

### ISSUE THREAD

**Issue by mugambika** [kubernetes/registry.k8s.io#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

Pull the image successfully.

### Debugging Information

`curl -v https://registry.k8s.io/v2/`

< HTTP/2 200
< docker-distribution-api-version: registry/2.0
< x-cloud-trace-context: 21234166028c5c60ab12af2b4f2ee520
< date: Tue, 06 Feb 2024 17:31:21 GMT
< content-type: text/html
< server: Google Frontend
< content-length: 0
< via: 1.1 google, 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenTheElder** [comment]
Please see the note at https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md unfortunately

**Comment by mugambika** [comment]
@BenTheElder Thanks for the quick response. Let me check on this.
