### ISSUE TITLE
K8's registry block server IP

### ISSUE THREAD

**Issue by Nabeel-Akhtar-Qbatch** [kubernetes/registry.k8s.io#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

It should take a pull from the K8's registry

### Debugging Information

Getting this on my server, however running succesfully locally.

sudo docker pull registry.k8s.io/pause:3.6.                 (Command)

Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>403 Forbidden</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Forbidden</h1>\n<h2>Your client does not have permission to get URL <code>/v2/pause/manifests/sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db</code> from this server.</h2>\n<h2></h2>\n</body></html>\n

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenTheElder** [comment]
Please see the debugging document, we have a note about this, it's not our code serving this response.

**Comment by BenTheElder** [comment]
You may have to use the mirroring guide as a workaround

**Comment by Nabeel-Akhtar-Qbatch** [comment]
@BenTheElder Please share debugging document or any other link that would help me . Thank you

**Comment by mrbobbytables** [comment]
@Nabeel-Akhtar-Qbatch links to it and the mirroring guide are in the README for this repo:
https://github.com/kubernetes/registry.k8s.io?tab=readme-ov-file#stability
