### ISSUE TITLE
PULL REQUEST FAIL WHEN TRYING TO PULL IMAGE FROM registry.k8s.io

### ISSUE THREAD

**Issue by amit3512** [kubernetes/registry.k8s.io#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

I want to pull all the images from the registry.k8s.io

### Debugging Information

I start ping the url with google  ip and It says cant reach host when i ping the site.

### Anything else?

nslook is working perfectly fine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenTheElder** [comment]
There's no actionable information here.

> I start ping the url with google ip and It says cant reach host when i ping the site.

Which URL? What "google IP"?

The issue template should say this for "Debugging information":
> Bugs MUST include debugging logs from general steps in https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md.

**Comment by Boston-of-Gilead** [comment]
> There's no actionable information here.
> 
> > I start ping the url with google ip and It says cant reach host when i ping the site.
> 
> Which URL? What "google IP"?
> 
> The issue template should say this for "Debugging information":
> 
> > Bugs MUST include debugging logs from general steps in https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md.

Hi,

Not OP but I think he's saying that the call to https://registry.k8s.io fails:

![image](https://github.com/kubernetes/registry.k8s.io/assets/26582745/a28e74e1-ef20-4e18-9393-db9ecd1c0807)

It looks like at some point https://registry.k8s.io was shut down and everything moved to https://github.com/kubernetes/registry.k8s.io . If I go to the old url via the browser it successfully redirects, but k8s doesn't seem to be able to traverse the same redirect.

OP's Google reference may refer to Google being the DNS server:

![image](https://github.com/kubernetes/registry.k8s.io/assets/26582745/bd11c744-156d-4b4d-a74e-64792c873b91)

If and I are having the same issue, I would state it as "k8s is still referencing an old url and the browser redirect doesn't seem to apply to k8s making the call to the old url." @amit3512 would you say that sounds like a fair re-phrase of your issue?

**Comment by BenTheElder** [comment]
> It looks like at some point https://registry.k8s.io/ was shut down and everything moved to https://github.com/kubernetes/registry.k8s.io .

No, registry.k8s.io is the URL, it serves a redirect at `/` because this is not an API endpoint for docker registries but it typically serves a page with the documentation for the service, which for us is the source repo here.

It serves container images under the registry API.

**Comment by BenTheElder** [comment]
NOTE: nslookup works on domains, `https://github.com/kubernetes/registry.k8s.io` isn't a URL, not a domain. `github.com.` is the domain. `nslookup registry.k8s.io` will work fine on google DNS servers.

Closing due to off-topic discussion and lack of information from the original issue.
