### ISSUE TITLE
switch to aws-sdk-go-v2

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/registry.k8s.io#289]
As pointed out by @dims in test-infra, the v1 SDK is going away.

The v2 SDK seems a bit differently weird ... I don't see go module compatible tags??

Anyhow, we should migrate.

/kind cleanup
/sig k8s-infra
/priority important-soon

https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/

**Comment by dims** [comment]
migration guide - https://aws.github.io/aws-sdk-go-v2/docs/migrating/

**Comment by BenTheElder** [comment]
`cmd/geranos/s3uploader.go` is the only place we actually use the AWS SDK in this repo, so it should be fairly straightforward.

**Comment by BenTheElder** [comment]
fixed in https://github.com/kubernetes/registry.k8s.io/pull/290
