### ISSUE TITLE
Please use subdomains for wildcard dns entries instead of path substitution

### ISSUE THREAD

**Issue by therevoman** [kubernetes/registry.k8s.io#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What did you expect to happen?

Customer could request a simple firewall change to allow all possible hosts behind registry.k8s.io

### Debugging Information

Customer in a restricted environment needed to pull csi-provisioner from registry.k8s.io.  Was unable to get docker or podman installed in a non-secure location to download and pass the image bundles in.  
Worked with firewall team to open up registry.k8s.io, only to find we also needed to add `something-central-docker.pkg.dev` and firewall team said they cannot do a partial hostname match in their rules preventing the request of `*-docker.pkg.dev`.  It was days later when we found out that the request was again forwarded to an AWS bucket.  

### Anything else?

I know we as a community like to stay modern and help guide customers to modern approaches, but having multiple redirects without a way to resolve (or use a simple match) to allow access to the artifacts seems a bit arrogant.
Either publish a complete list of redirect sites or change to subdomains.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenTheElder** [comment]
Please read our README

**Comment by BenTheElder** [comment]
> I know we as a community like to stay modern and help guide customers to modern approaches, but having multiple redirects without a way to resolve (or use a simple match) to allow access to the artifacts seems a bit arrogant.

.. this is a free service operated by volunteers, running on donated vendor resources.

We don't currently maintain a list of backends and they are subject to change at anytime to prioritize keeping them online at anytime. There's a detailed description of this at the top of the readme, which is the landing page for https://registry.k8s.io

There are many alternatives for your paying client.

We have found in the past that users will not switch when we ask them politely to migrate to a new more cost effective host, so we're not backing ourselves into any corners this time. It's a free service.

**Comment by BenTheElder** [comment]
The reason we do redirects to multiple backends is also outlined in detail in the docs.

**Comment by dims** [comment]
> Either publish a complete list of redirect sites or change to subdomains.

Sorry no.

/close
