### ISSUE TITLE
Alerting for production deployment?

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/registry.k8s.io#75]
https://github.com/kubernetes/kubernetes/pull/109938#pullrequestreview-990722588

**Comment by ameukam** [comment]
Alerts added for `registry.k8s.io` and `registry-sandbox.k8s.io`: https://github.com/kubernetes/k8s.io/pull/4145.

Follow-up would be to define SLOs and add latency-based alerts.

**Comment by BenTheElder** [comment]
this is a dupe of https://github.com/kubernetes/registry.k8s.io/issues/17
/triage duplicate
/close
