### ISSUE TITLE
Collecting log data for Data Studio reports to show registry.k8s.io success

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/registry.k8s.io#90]
Once traffic is redirected via oci-proxy it would make sense to create Data Studio reports to show the success of the project.

Initially the cost saving should be visible in the monthly K8s Infra GCP Billing report.  However, as soon as head room has been created in monthly expenditure work could continue on mitigating the remaining K8s Infra componentes to community infa, which would again increase spending. 

This would created a moving target, making it difficult to show the real cost saving achieved over the next months

For this we would need the logs for oci-proxy, reg.k8s.io as well as die log data from the AWS S3 buckets. Further processing of the data would allow us to match SHA and K8s release version, which would give insight into cost per release.

@BobyMCbobs @hh

**Comment by BobyMCbobs** [comment]
Requires: https://github.com/kubernetes/k8s.io/issues/3929

**Comment by Riaankl** [comment]
/retitle Collecting log data for Data Studio reports to show registry.k8s.io success

**Comment by BenTheElder** [comment]
We should be able to see the change in GCR/GCS costs for k8s-artifacts-prod, which is the metric we're actually after.

Soon all traffic should flow through this project and the net cost change will still be the real success metric.

Even if we move X% of traffic to AWS that doesn't mean we moved X% cost, we should just look at the cost directly.

We can already see the breakdown of costs by specific GCP projects and services in the data studio report.

The net cost change is cost change for k8s-artifacts-prod + cost change for oci-proxy-prod.

**Comment by ameukam** [comment]
Now we serve traffic from AWS for non-GCP traffic, we need to rethink how we want to demonstrate success of registry.k8s.io.
Closing this for now.
/close
