### ISSUE TITLE
Rename this repo to registry.k8s.io

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/registry.k8s.io#94]
This repo is for an important piece of software that will be heavily used by the community when running.
I don't believe the name _oci-proxy_ currently chosen reflects the behaviour or function of the webserver, as it doesn't directly implement the OCI spec and does not act as a proxy but functions as a redirect with handling particular paths and headers.

I would suggest that the project live in _kubernetes-sigs/registry.k8s.io_, so that it is very clear it's purpose.

Keen to hear thoughts!

**Comment by BenTheElder** [comment]
periods in the name is unusual at least, does github allow this?

I wouldn't block a rename to something more appropriate, but I also wouldn't sign up for this because the effort to do so tends to be pretty high (need to track down inbound links, CI configs, etc.)

cc @dims @ameukam

**Comment by BobyMCbobs** [comment]
> periods in the name is unusual at least, does github allow this?

@BenTheElder periods in names are allowed, for example here's ii's repo for the test implementations:
https://github.com/ii/registry.k8s.io

**Comment by endocrimes** [comment]
It's used in Kubernetes: https://github.com/kubernetes/k8s.io/ - that being said, I think I'd be more for relocating this into the main k org at the same time as a rename.

(by the time it becomes the main way to get our release artifacts being in the sigs org does feel a little hidden)

**Comment by dims** [comment]
@BobyMCbobs i would run this by our github admins ( https://github.com/kubernetes/community/tree/master/github-management#github-administration-team )

+1 from me if you wish to own all the steps needed :)

**Comment by BobyMCbobs** [comment]
I added a message in the _github-management_ channel regarding this issue
https://kubernetes.slack.com/archives/C01672LSZL0/p1660172586179179

**Comment by cblecker** [comment]
Repo renames can be done by opening a request in the kubernetes/org repo: https://github.com/kubernetes/org/issues/new/choose

Our guidelines for repos are here: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md

For repos in kubernetes-sigs, the name is flexible and can be decided on by the sigs as long as it's descriptive enough for what it actually does. In this case, sig-k8s-infra can choose a name (and that name needs to be signed off by the TLs).

For repos in the main kubernetes org, it's a little different. Both the name, as well as the purpose of the repo, need to be signed off by sig-arch in addition to the owning sig. Typically, unless the repo is considered kubernetes core (as listed in that repo guidance), kubernetes-sigs is the right place for it.

**Comment by hh** [comment]
I think `registry.k8s.io` likely fits under project-wide infrastructure, and the purpose would be pretty succinct :

> gitHub-management/kubernetes-repositories.md
> Core Repositories:
>  … Additionally, the kubernetes.io website, k8s.io machinery, and other project-wide infrastructure will remain in the kubernetes github organization.

**Comment by BobyMCbobs** [comment]
Submitted a k/org issue for this here
https://github.com/kubernetes/org/issues/3605

**Comment by Riaankl** [comment]
REQUEST: Migrate oci-proxy [#3605](https://github.com/kubernetes/org/issues/3605)

**Comment by BenTheElder** [comment]
We'll need to update the CI jobs.

**Comment by Riaankl** [comment]
/closed
Resolve in https://github.com/kubernetes/org/issues/3605
